apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
  namespace: fursight
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
        - name: zookeeper
          image: bitnami/zookeeper:3.8
          ports:
            - containerPort: 2181
          env:
            - name: ALLOW_ANONYMOUS_LOGIN
              value: "yes"
          volumeMounts:
            - name: zookeeper-data-volume
              mountPath: /bitnami
      volumes:
        - name: zookeeper-data-volume
          persistentVolumeClaim:
            claimName: zookeeper-data-pvc
