# metallb-config.yaml
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default-pool
  namespace: metallb-system
spec:
  addresses:
    - 172.22.0.200-172.22.0.250 #  docker network inspect k3d-fursight-ai | grep Subnet    "Subnet": "172.22.0.0/16",
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: default
  namespace: metallb-system